### PR TITLE
Update selected value when setting default value on Select

### PR DESCRIPTION
**Pull request by aaronrogers**
There was a problem where if the default value for a Select was updated, the selected value in the dropdown didn't change.  This is an attempt to fix that.

Also, installing `figma-plugin-ds` via the url `https://github.com/thomas-lowry/figma-plugin-ds.git` didn't work for me.  npm was complaining of the URL not containing a `package.json` file.  I instead used `napa` to install `figma-plugin-ds` after `npm install`.  It also made for a change in the `build-styles` script path.

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Thanks for contribution!
I'm not very excited to land changes about `napa`. Could you provide more details about what kind of error do you get, and what npm version do you use? I've tested with yarn and npm, no any issues

**Comment by aaronrogers** [comment]
I totally agree, I didn't want to add `napa`.

The errors have changed since I last tried this.  I'm not sure if it's because of some system changes I made recently.

- `npm install` runs successfully
- `npm run build` fails with...

```
> react-figma-plugin-ds@1.0.3 build /Users/{..snip..}/react-figma-plugin-ds
> rm -rf ./dist && tsc && npm run build-styles && webpack


> react-figma-plugin-ds@1.0.3 build-styles /Users/{..snip..}/react-figma-plugin-ds
> mkdir -p styles/ && cp -r node_modules/figma-plugin-ds/*.css styles/

cp: node_modules/figma-plugin-ds/*.css: No such file or directory
```

When I look in `node_modules/figma-plugin-ds` I see



There are no CSS files in the root directory.

If you want to cherrypick the changes to `Select.tsx` (assuming they're good) then that'd be all I need.

**Comment by alexandrtovmach** [comment]
@aaronrogers thanks for investigation. Yeah, problem is already resolved and it's because original repo did some updates and added _package.json_

**Comment by alexandrtovmach** [comment]
They also did some refactor, that is not backward compatible, so I'm going to investigate and fix some things soon. Best choice for this PR is to drop changes related to napa and installation and keep only Select updates. Could you do this?

**Comment by aaronrogers** [comment]
That's what I was thinking as well.

I'll see if I can drop changes, or I'll close this PR and open a new one.

**Comment by aaronrogers** [comment]
Ok, `napa` changes were removed.

**Pull request merged**
